services:
    _defaults:
        autowire: true
        autoconfigure: true

    netliva.filehelper.image:
        alias: Netliva\SymfonyFileHelperBundle\Services\NetlivaImageHelper
        public: true

    Netliva\SymfonyFileHelperBundle\Services\NetlivaImageHelper:
        class: Netliva\SymfonyFileHelperBundle\Services\NetlivaImageHelper
        public: false
        autowire: true
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }

    netliva.filehelper.file:
        alias: Netliva\SymfonyFileHelperBundle\Services\NetlivaFileHelper
        public: true

    Netliva\SymfonyFileHelperBundle\Services\NetlivaFileHelper:
        class: Netliva\SymfonyFileHelperBundle\Services\NetlivaFileHelper
        public: false
        autowire: true
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: twig.extension }

    # Controller services
    Netliva\SymfonyFileHelperBundle\Controller\ImageController:
        public: true
        autowire: true
        autoconfigure: true

    Netliva\SymfonyFileHelperBundle\Controller\FileController:
        public: true
        autowire: true
        autoconfigure: true
